import os
os.system("pip install -r setup/requirements.txt")
os.system("mkdir base_images")
os.system("mkdir base_labels")
# os.system('mkdir -p data\\test')
# os.system('mkdir -p data\\train')
# os.system('mkdir -p data\\valid')
# os.system("mkdir -p data\\test\\labels")
# os.system("mkdir -p data\\test\\images")
# os.system("mkdir -p data\\train\\labels")
# os.system("mkdir -p data\\train\\images")
# os.system("mkdir -p data\\valid\\labels")
# os.system("mkdir -p data\\valid\\images")