import os
os.system("pip install -r setup/requirements.txt")
os.system("mkdir base_images")
os.system("mkdir base_labels")
os.system('mkdir data\\test')
os.system('mkdir data\\train')
os.system('mkdir data\\valid')
os.system("mkdir data\\test\\labels")
os.system("mkdir data\\test\\images")
os.system("mkdir data\\train\\labels")
os.system("mkdir data\\train\\images")
os.system("mkdir data\\valid\\labels")
os.system("mkdir data\\valid\\images")